---
title: "behavior_hypotheses_tests_srndnaUGR"
author: "Jen Yang"
date: "2024-11-12, last modified 2024-11-12"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug"

ROI_mean_name = "imaging_plots_SANS"
data_dir = paste(gitrepo_path, ROI_mean_name, sep = "/")
figure_dir = paste(gitrepo_path,"behavioral_analyses/figures/SANS", sep = "/")

list_fmri_df = read.csv(paste(gitrepo_path, "behavioral_analyses/data", "participant_fmri.csv", sep = "/"),
                          header = T) %>% 
  mutate(age_bi = case_when(age <= 36 ~ "younger",
                            age > 36 ~ "older")) %>% 
  select(participant_id, age_bi)

participant_wide_df = read.csv(paste(gitrepo_path, "behavioral_analyses/data", "participant_wide.csv", sep = "/")) %>% 
  select(-c("age", "sex", "trial_total", "Include"))
```

## plot font setup
```{r}
# my_colors <- RColorBrewer::brewer.pal(9, "Blues")[c(5,8)]
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14
legend_all = 12
alpha_level = 0.8
fig_color = "#117733"

w = 5
h = 4
```

# alpha (envy)
## in-out_alpha_ageBI_act
### prepare data
```{r}
computer_name = "in-out_alpha_age_act_z2_c1_type-act_cope-02.txt"
in_name = "in-out_alpha_age_act_z2_c1_type-act_cope-04.txt"
out_name = "in-out_alpha_age_act_z2_c1_type-act_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "computer",
         age_bi = list_fmri_df$age_bi,
         V1_computer = V1) %>% 
  select(participant_id, age_bi, V1_computer)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "ingroup",
         V1_ingroup = V1) %>% 
  select(V1_ingroup)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "outgroup",
         V1_outgroup = V1) %>% 
  select(V1_outgroup)

all_brain_df = cbind(computer_df,
                     in_df, out_df)

data_plot_df = all_brain_df %>% 
  merge(., participant_wide_df, by.x = "participant_id") %>% 
  mutate(brain_contrast = V1_ingroup - V1_outgroup,
         alpha_contrast = ingroup_alpha - outgroup_alpha,
         age_bi = as.factor(age_bi)) %>% 
  select(participant_id, age_bi, brain_contrast, alpha_contrast)

data_plot_df$age_bi = relevel(data_plot_df$age_bi, ref = "younger")
```

### plot
```{r}
### setup
x_label = "Inequality Senstivity, ingroup > outgroup"
y_label = "Activation, ingroup > outgroup\n(fairness modulated)"
brain_name = "in-out_alpha_age_act_z2_c1_type-act"

# group_summary <- data_plot_df %>%
#   group_by(type, age_bi) %>%
#   summarise(mean = mean(V1), se = sd(V1)/sqrt(nrow(list_fmri_df)),
#             .groups = "keep")

p_scatter =
  ggplot(data_plot_df, aes(alpha_contrast, brain_contrast, 
                                     color = age_bi)) + 
  geom_point(alpha = 0.6, size = 1.5) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              alpha = 0.2) +
  labs(x = x_label, y = y_label, color = "Age Group") +
  coord_cartesian(xlim=c(-1, 2)) +
  # scale_color_manual(name = "Make Others Feel Worse", values = fig_color) +
  # scale_fill_manual(name = "Make Others Feel Worse", values = fig_color) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))
        # legend.position="bottom left", legend.box = "horizontal")
        # legend.position="none")

ggsave(paste(figure_dir, paste(brain_name, "scatter.png", sep = "_"), 
             sep = "/"), p_scatter, width = w, height = h)
```

## in-out_alpha_age_ecn_z1_c1_type-nppi-ecn
### prepare data
```{r}
computer_name = "in-out_alpha_age_ecn_z1_c1_type-nppi-ecn_cope-02.txt"
in_name = "in-out_alpha_age_ecn_z1_c1_type-nppi-ecn_cope-04.txt"
out_name = "in-out_alpha_age_ecn_z1_c1_type-nppi-ecn_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "computer",
         age_bi = list_fmri_df$age_bi,
         V1_computer = V1) %>% 
  select(participant_id, age_bi, V1_computer)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "ingroup",
         V1_ingroup = V1) %>% 
  select(V1_ingroup)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "outgroup",
         V1_outgroup = V1) %>% 
  select(V1_outgroup)

all_brain_df = cbind(computer_df,
                     in_df, out_df)

data_plot_df = all_brain_df %>% 
  merge(., participant_wide_df, by.x = "participant_id") %>% 
  mutate(brain_contrast = V1_ingroup - V1_outgroup,
         alpha_contrast = ingroup_alpha - outgroup_alpha,
         age_bi = as.factor(age_bi)) %>% 
  select(participant_id, age_bi, brain_contrast, alpha_contrast)

data_plot_df$age_bi = relevel(data_plot_df$age_bi, ref = "younger")
```

### plot
```{r}
### setup
x_label = "Inequality Senstivity, ingroup > outgroup"
y_label = "ECN-Precuneus, ingroup > outgroup\n(fairness modulated)"
brain_name = "in-out_alpha_age_ecn_z1_c1_type-nppi-ecn"

# group_summary <- data_plot_df %>%
#   group_by(type, age_bi) %>%
#   summarise(mean = mean(V1), se = sd(V1)/sqrt(nrow(list_fmri_df)),
#             .groups = "keep")

p_scatter =
  ggplot(data_plot_df, aes(alpha_contrast, brain_contrast, 
                           color = age_bi)) + 
  geom_point(alpha = 0.6, size = 1.5) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              alpha = 0.2) +
  labs(x = x_label, y = y_label, color = "Age Group") +
  coord_cartesian(xlim=c(-1, 2)) +
  # scale_color_manual(name = "Make Others Feel Worse", values = fig_color) +
  # scale_fill_manual(name = "Make Others Feel Worse", values = fig_color) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))
# legend.position="bottom left", legend.box = "horizontal")
# legend.position="none")

ggsave(paste(figure_dir, paste(brain_name, "scatter.png", sep = "_"), 
             sep = "/"), p_scatter, width = w, height = h)
```

# Epsilon (Norm Adaptation)
## hum-com_epsilon_age_ecn_z2_c3_type-nppi-ecn
### prepare data
```{r}
computer_name = "hum-com_epsilon_age_ecn_z2_c3_type-nppi-ecn_cope-02.txt"
in_name = "hum-com_epsilon_age_ecn_z2_c3_type-nppi-ecn_cope-04.txt"
out_name = "hum-com_epsilon_age_ecn_z2_c3_type-nppi-ecn_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "computer",
         age_bi = list_fmri_df$age_bi,
         V1_computer = V1) %>% 
  select(participant_id, age_bi, V1_computer)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "ingroup",
         V1_ingroup = V1) %>% 
  select(V1_ingroup)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "outgroup",
         V1_outgroup = V1) %>% 
  select(V1_outgroup)

all_brain_df = cbind(computer_df,
                     in_df, out_df)

data_plot_df = all_brain_df %>% 
  merge(., participant_wide_df, by.x = "participant_id") %>% 
  mutate(brain_contrast = V1_ingroup + V1_outgroup - 2*V1_computer,
         epsilon_contrast = human_epsilon - computer_epsilon,
         age_bi = as.factor(age_bi)) %>% 
  select(participant_id, age_bi, brain_contrast, epsilon_contrast)

data_plot_df$age_bi = relevel(data_plot_df$age_bi, ref = "younger")
```

### plot
```{r}
### setup
x_label = "Norm Adaptation, human > computer"
y_label = "ECN-dlPFC, human > computer\n(fairness modulated)"
brain_name = "hum-com_epsilon_age_ecn_z2_c3_type-nppi-ecn"

# group_summary <- data_plot_df %>%
#   group_by(type, age_bi) %>%
#   summarise(mean = mean(V1), se = sd(V1)/sqrt(nrow(list_fmri_df)),
#             .groups = "keep")

p_scatter =
  ggplot(data_plot_df, aes(epsilon_contrast, brain_contrast, 
                           color = age_bi)) + 
  geom_point(epsilon = 0.6, size = 1.5) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              epsilon = 0.2) +
  labs(x = x_label, y = y_label, color = "Age Group") +
  # coord_cartesian(xlim=c(-2, 2)) +
  # scale_color_manual(name = "Make Others Feel Worse", values = fig_color) +
  # scale_fill_manual(name = "Make Others Feel Worse", values = fig_color) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))
# legend.position="bottom left", legend.box = "horizontal")
# legend.position="none")

ggsave(paste(figure_dir, paste(brain_name, "scatter.png", sep = "_"),
             sep = "/"), p_scatter, width = w, height = h)
```

## hum-com_epsilon_age_dmn_z2_c1_type-nppi-dmn
### prepare data
```{r}
computer_name = "hum-com_epsilon_age_dmn_z2_c1_type-nppi-dmn_cope-02.txt"
in_name = "hum-com_epsilon_age_dmn_z2_c1_type-nppi-dmn_cope-04.txt"
out_name = "hum-com_epsilon_age_dmn_z2_c1_type-nppi-dmn_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "computer",
         age_bi = list_fmri_df$age_bi,
         V1_computer = V1) %>% 
  select(participant_id, age_bi, V1_computer)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "ingroup",
         V1_ingroup = V1) %>% 
  select(V1_ingroup)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "outgroup",
         V1_outgroup = V1) %>% 
  select(V1_outgroup)

all_brain_df = cbind(computer_df,
                     in_df, out_df)

data_plot_df = all_brain_df %>% 
  merge(., participant_wide_df, by.x = "participant_id") %>% 
  mutate(brain_contrast = V1_ingroup + V1_outgroup - 2*V1_computer,
         epsilon_contrast = human_epsilon - computer_epsilon,
         age_bi = as.factor(age_bi)) %>% 
  select(participant_id, age_bi, brain_contrast, epsilon_contrast)

data_plot_df$age_bi = relevel(data_plot_df$age_bi, ref = "younger")
```

### plot
```{r}
### setup
x_label = "Norm Adaptation, human > computer"
y_label = "DMN-dlPFC, human > computer\n(fairness modulated)"
brain_name = "hum-com_epsilon_age_dmn_z2_c1_type-nppi-dmn"

# group_summary <- data_plot_df %>%
#   group_by(type, age_bi) %>%
#   summarise(mean = mean(V1), se = sd(V1)/sqrt(nrow(list_fmri_df)),
#             .groups = "keep")

p_scatter =
  ggplot(data_plot_df, aes(epsilon_contrast, brain_contrast, 
                           color = age_bi)) + 
  geom_point(epsilon = 0.6, size = 1.5) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              epsilon = 0.2) +
  labs(x = x_label, y = y_label, color = "Age Group") +
  # coord_cartesian(xlim=c(-2, 2)) +
  # scale_color_manual(name = "Make Others Feel Worse", values = fig_color) +
  # scale_fill_manual(name = "Make Others Feel Worse", values = fig_color) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))
# legend.position="bottom left", legend.box = "horizontal")
# legend.position="none")

ggsave(paste(figure_dir, paste(brain_name, "scatter.png", sep = "_"),
             sep = "/"), p_scatter, width = w, height = h)
```

## in-out_epsilon_age_dmn_z1_c2_type-nppi-dmn
### prepare data
```{r}
computer_name = "in-out_epsilon_age_dmn_z1_c2_type-nppi-dmn_cope-02.txt"
in_name = "in-out_epsilon_age_dmn_z1_c2_type-nppi-dmn_cope-04.txt"
out_name = "in-out_epsilon_age_dmn_z1_c2_type-nppi-dmn_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "computer",
         age_bi = list_fmri_df$age_bi,
         V1_computer = V1) %>% 
  select(participant_id, age_bi, V1_computer)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "ingroup",
         V1_ingroup = V1) %>% 
  select(V1_ingroup)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = list_fmri_df$participant_id,
         type = "outgroup",
         V1_outgroup = V1) %>% 
  select(V1_outgroup)

all_brain_df = cbind(computer_df,
                     in_df, out_df)

data_plot_df = all_brain_df %>% 
  merge(., participant_wide_df, by.x = "participant_id") %>% 
  mutate(brain_contrast = V1_ingroup - V1_outgroup,
         epsilon_contrast = ingroup_epsilon - outgroup_epsilon,
         age_bi = as.factor(age_bi)) %>% 
  select(participant_id, age_bi, brain_contrast, epsilon_contrast)

data_plot_df$age_bi = relevel(data_plot_df$age_bi, ref = "younger")
```

### plot
```{r}
### setup
x_label = "Norm Adaptation, ingroup > outgroup"
y_label = "DMN-OFC, ingroup > outgroup\n(fairness modulated)"
brain_name = "in-out_epsilon_age_dmn_z1_c2_type-nppi-dmn"

# group_summary <- data_plot_df %>%
#   group_by(type, age_bi) %>%
#   summarise(mean = mean(V1), se = sd(V1)/sqrt(nrow(list_fmri_df)),
#             .groups = "keep")

p_scatter =
  ggplot(data_plot_df, aes(epsilon_contrast, brain_contrast, 
                           color = age_bi)) + 
  geom_point(epsilon = 0.6, size = 1.5) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              epsilon = 0.2) +
  labs(x = x_label, y = y_label, color = "Age Group") +
  # coord_cartesian(xlim=c(-1, 2)) +
  # scale_color_manual(name = "Make Others Feel Worse", values = fig_color) +
  # scale_fill_manual(name = "Make Others Feel Worse", values = fig_color) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))
# legend.position="bottom left", legend.box = "horizontal")
# legend.position="none")

ggsave(paste(figure_dir, paste(brain_name, "scatter.png", sep = "_"), 
             sep = "/"), p_scatter, width = w, height = h)
```

