---
title: "behavior_hypotheses_tests_srndnaUGR"
author: "Jen Yang"
date: "2024-11-12, last modified 2024-11-12"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/"

ROI_mean_name = "imaging_plots_SJDM"
data_dir = paste(gitrepo_path, ROI_mean_name, sep = "/")
figure_dir = paste(gitrepo_path,"behavioral_analyses/figures/SANS", sep = "/")

participant_df = read.csv(paste(gitrepo_path, "behavioral_analyses/data", "participant_fmri.csv", sep = "/"),
                          header = T)
```

## plot font setup
```{r}
# my_colors <- RColorBrewer::brewer.pal(9, "Blues")[c(5,8)]
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14
legend_all = 12
alpha_level = 0.8

w = 4.3
h = 4
```

```{r}
### setup
fig_color = "#117733"
x_label = "Social Closeness"
y_label = "DMN seed, in > out, fairness para"
brain_name = "in-out_epsilon_age_dmn_5"
###
computer_name = "in-out_epsilon_age_dmn_5_type-nppi-dmn_cope-02.txt"
in_name = "in-out_epsilon_age_dmn_5_type-nppi-dmn_cope-04.txt"
out_name = "in-out_epsilon_age_dmn_5_type-nppi-dmn_cope-06.txt"

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = participant_df$participant_id,
         type = "computer") %>% 
  select(participant_id, V1, type)

in_df = read.table(paste(data_dir,in_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = participant_df$participant_id,
         type = "ingroup") %>% 
  select(participant_id, V1, type)

out_df = read.table(paste(data_dir,out_name,sep = '/'),sep=" ",header=F) %>% 
  mutate(participant_id = participant_df$participant_id,
         type = "outgroup")  %>% 
  select(participant_id, V1, type)

data_plot_df = rbind(computer_df, in_df, out_df) 

ggplot(data = plot_df, aes(x = IOS_FvS, y = brain)) + 
  geom_point(alpha = alpha_level, 
             color = fig_color,
             size = 1.5) + 
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE, 
              fill = fig_color,
              linetype = "solid", 
              linewidth = 2,
              color = fig_color, alpha = 0.2) +
  labs(x = x_label, y = y_label) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"))

# ggsave(paste(fig_save_dir, paste(brain_name, "scatter.png", sep = "_"), sep = "/"), width = w, height = h)
```

