---
title: "fmri plot for SANS talk with brain contrasts broken down"
author: "Jen Yang"
date: "2025-04-21, last modified 2025-04-21"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
library(LMMstar)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")

ROImean_dir = "/Users/momocco/Documents/GitHub/srndna-ug/imaging_plots_SANS"

list_fmri_df = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"),
                          header = T) %>% dplyr::select(subjID)

participant_check_df = read.csv(paste(data_dir, "participant_check.csv", sep = "/"), header = T)

participant_demo_df = 
  merge(list_fmri_df, participant_check_df, by.x = "subjID", by.y = "participant_id", all.x = T) %>% 
  mutate(age_bi = case_when(age <= 36 ~ "younger", age > 36 ~ "older"),
         age_bi = relevel(as.factor(age_bi), ref = "younger"))

## load tsnr, fd_mean, and RT
sub_control_df = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"),
                          header = T) %>% 
  select(subjID, tsnr, fd_mean, RT)

control_vars = colnames(sub_control_df)[-1]
```

# plot param setup
```{r}
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14

legend_all = 12

annotate_text = 4
axis_line_width = 1
fit_line_width = 2

data_point_alpha = 0.5
data_point_size = 3*0.8

mean_point_size = 3

summary_point_alpha = 1
summary_point_size = 3

annotate_text = 4

w = 5
h = 4
```

# dmn, cope7, in-out c3 y-o, paracingulate gyrus?, -13.3, 34, 27.8 (aCC?, COG -3.6 33.4 32.9)
## prep original data
### load data
```{r}
## data prep
in_name = "dmn_p_in-out_y-o_type-nppi-dmn_cope-04.txt"
out_name = "dmn_p_in-out_y-o_type-nppi-dmn_cope-06.txt"

in_ROI = read.table(paste(ROImean_dir, in_name, sep = '/'),sep=" ",header=F)
out_ROI = read.table(paste(ROImean_dir, out_name, sep = '/'),sep=" ",header=F)
```

### ingroup
```{r}
in_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
              in_ROI = in_ROI$V1, # for packed interaction, y axis = contrasted brain activity
              ROI = in_ROI$V1, # for unpacked interaction, y axis = no-contrast brain activity
              group = as.factor("ingroup")) # for unpacked interaction, y axis = no-contrast brain activity

in_df = merge(in_df, sub_control_df, by = "subjID")

## get partial residual
LMM_df = in_df
formula_string = "ROI ~ age_bi + tsnr + fd_mean + RT"
formula_LMM = as.formula(formula_string)
focal_var_names = c("(Intercept)", "age_bi")

pres_LMM_fit = lmm(formula_LMM, data = LMM_df)
in_df$ROI_pres <- residuals(pres_LMM_fit, type = "partial", 
                         variable = focal_var_names)

in_plot_df = in_df %>% 
  select(subjID, ROI_pres, age_bi, group)
```

### outgroup
```{r}
out_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
               out_ROI = out_ROI$V1, # for packed interaction, y axis = contrasted brain activity
               ROI = out_ROI$V1, # for unpacked interaction, y axis = no-contrast brain activity
               group = as.factor("outgroup")) # for unpacked interaction, y axis = no-contrast brain activity
out_df = merge(out_df, sub_control_df, by = "subjID")

## get partial residual
LMM_df = out_df
formula_string = "ROI ~ age_bi + tsnr + fd_mean + RT"
formula_LMM = as.formula(formula_string)
focal_var_names = c("(Intercept)", "age_bi")

pres_LMM_fit = lmm(formula_LMM, data = LMM_df)
out_df$ROI_pres <- residuals(pres_LMM_fit, type = "partial", 
                         variable = focal_var_names)

out_plot_df = out_df %>% 
  select(subjID, ROI_pres, age_bi, group)
```

## put together plotting df
```{r}
plot_df = rbind(in_plot_df, out_plot_df)

## prepare summary data for plotting means, error bars, and lines
summary_plot_df <- plot_df %>%
  group_by(age_bi, group) %>%
  summarise(mean_ROI_pres = mean(ROI_pres, na.rm = TRUE),
    se_ROI_pres = sd(ROI_pres, na.rm = TRUE) / sqrt(n()))
```

## ggplot and save
```{r}
x_label = ""
y_label = "DMN-dACC PPI\nsensitivity to fairness"
title_label = ""

color_age_label = "Age"
color_age = c("older" = "#006900", "younger"= "#00d000")

figure_name = "DMN_dACC_in-out_age_NoBehCov_noContrast"

p_scatter = 
  ggplot() +
  geom_jitter(data = plot_df, aes(x = group, y = ROI_pres, color = age_bi),
              alpha = data_point_alpha, 
              width = 0.1, size = data_point_size) + # Adjust jitter width for categorical X
  geom_point(data = summary_plot_df, aes(x = group, y = mean_ROI_pres), 
             size = mean_point_size, alpha = data_point_alpha, shape = 18) +
  geom_errorbar(data = summary_plot_df, 
                aes(x = group, 
                    ymin = mean_ROI_pres - se_ROI_pres, ymax = mean_ROI_pres + se_ROI_pres),
                width = 0.1) +
  scale_color_manual(values = color_age) +
  labs(x = x_label, y = y_label, color = color_age_label, title = title_label) +
  # labs(x = x_label, y = y_label, color = color_label, title = NULL) +
  geom_line(data = summary_plot_df, # Connect means with a line
            aes(x = group, y = mean_ROI_pres, group = age_bi, color = age_bi), 
            linewidth = fit_line_width/2) +
  theme_classic() +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        legend.title = element_text(face = "bold"),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold")) 

ggsave(paste(figure_dir, paste(figure_name, "scatter_classic.png", sep = "_"),
             sep = "/"), p_scatter, width = w*1.1, height = h)
```

# ecn, in-out, sensitivity_logit * age, frontal pole/mpfc?
## prepare df for ggplot
### load data
```{r}
## data prep
in_name = "ecn_p_in-out_o-y_sens-logit_type-nppi-ecn_cope-04.txt"
out_name = "ecn_p_in-out_o-y_sens-logit_type-nppi-ecn_cope-06.txt"

in_ROI = read.table(paste(ROImean_dir, in_name, sep = '/'), sep=" ",header=F)
out_ROI = read.table(paste(ROImean_dir, out_name, sep = '/'), sep=" ",header=F)

sensitivity_name = "in_out_sensitivity_full_logit.csv"

in_out_rand_df = read.csv(paste(data_dir, sensitivity_name, sep = "/"), header = TRUE)
```

### ingroup
```{r}
in_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
              in_ROI = in_ROI$V1, # for packed interaction, y axis = contrasted brain activity
              ROI = in_ROI$V1, # for unpacked interaction, y axis = no-contrast brain activity
              group = as.factor("ingroup")) # for unpacked interaction, y axis = no-contrast brain activity

in_df = merge(in_df, sub_control_df, by = "subjID")

## get partial residual
LMM_df = in_df
formula_string = "ROI ~ age_bi + tsnr + fd_mean + RT"
formula_LMM = as.formula(formula_string)
focal_var_names = c("(Intercept)", "age_bi")

pres_LMM_fit = lmm(formula_LMM, data = LMM_df)
in_df$ROI_pres <- residuals(pres_LMM_fit, type = "partial", 
                         variable = focal_var_names)

in_plot_df = in_df %>% 
  mutate(sensitivity_norm = in_out_rand_df$ingroup) %>% 
  select(subjID, ROI_pres, sensitivity_norm, age_bi, group)
```

### outgroup
```{r}
out_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
              out_ROI = out_ROI$V1, # for packed interaction, y axis = contrasted brain activity
              ROI = out_ROI$V1, # for unpacked interaction, y axis = no-contrast brain activity
              group = as.factor("outgroup")) # for unpacked interaction, y axis = no-contrast brain activity

out_df = merge(out_df, sub_control_df, by = "subjID")

## get partial residual
LMM_df = out_df
formula_string = "ROI ~ age_bi + tsnr + fd_mean + RT"
formula_LMM = as.formula(formula_string)
focal_var_names = c("(Intercept)", "age_bi")

pres_LMM_fit = lmm(formula_LMM, data = LMM_df)
out_df$ROI_pres <- residuals(pres_LMM_fit, type = "partial", 
                            variable = focal_var_names)

out_plot_df = out_df %>% 
  mutate(sensitivity_norm = in_out_rand_df$outgroup) %>% 
  select(subjID, ROI_pres, sensitivity_norm, age_bi, group)
```

## put together plotting df
```{r}
plot_df = rbind(in_plot_df, out_plot_df)
```


## plot and save
```{r}
x_label = "Norm Violation Sensitivity"
y_label = "ECN-mPFC connectivit\nsensitivity to fairness"
title_label = "ECN-mPFC Connectivity's Sensitivity to Fairness\nIngroup > Outgroup"

color_age_label = "Age"
color_age = c("older" = "#003c66", "younger"= "#0098ff")

figure_name = "ECN_mPFC_in-out_age_BehFairSensitivityFull"

# p_scatter =
ggplot(plot_df, aes(x = sensitivity_norm, y = ROI_pres, color = age_bi)) +
  geom_point(alpha = data_point_alpha, size = data_point_size, show.legend = FALSE) +
  geom_smooth(formula = "y~x", method = "lm", 
              se = TRUE,
              linetype = "solid",
              linewidth = 2, 
              alpha = 0.2) +
  facet_grid(. ~ group) +
scale_color_manual(values = color_age) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme_classic() +
  labs(x = x_label, y = y_label, color = color_age_label, title = title_label) +
  # labs(x = x_label, y = y_label, color = color_label, title = NULL) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        legend.title = element_text(face = "bold"),
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold")
        # strip.background = element_rect(colour="black", fill="white", 
        #                                size=1.5, linetype="solid")
        )

ggsave(paste(figure_dir, paste(figure_name, "scatter_classic.png", sep = "_"),
             sep = "/"), p_scatter, width = w*1.1, height = h)
```




# end of code