---
title: "fmri plot for SANS talk"
author: "Jen Yang"
date: "2025-04-10, last modified 2025-04-10"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")

ROImean_dir = "/Users/momocco/Documents/GitHub/srndna-ug/imaging_plots_SANS"

list_fmri_df = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"),
                          header = T) %>% dplyr::select(subjID)

participant_check_df = read.csv(paste(data_dir, "participant_check.csv", sep = "/"), header = T)

participant_demo_df = merge(list_fmri_df, participant_check_df, 
                            by.x = "subjID", by.y = "participant_id", all.x = T) %>% 
  mutate(age_bi = case_when(age <= 36 ~ "younger",
                            age > 36 ~ "older"))

## load tsnr, fd_mean, and RT
sub_control_df = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"),
                          header = T) %>% 
  select(subjID, tsnr, fd_mean, RT)
```

# plot font setup
```{r}
# my_colors <- RColorBrewer::brewer.pal(9, "Blues")[c(5,8)]
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14
legend_all = 12
alpha_level = 0.8
fig_color = "#117733"
annotate_text = 4
line_width = 1
point_size = 3

w = 5
h = 4
```

# Para, dmn, cope7, in-out c3 y-o, paracingulate gyrus?, -13.3, 34, 27.8 (aCC?, COG -3.6 33.4 32.9)
## prepare df for ggplot
```{r}
in_name = "dmn_p_in-out_y-o_type-nppi-dmn_cope-04.txt"
out_name = "dmn_p_in-out_y-o_type-nppi-dmn_cope-06.txt"

in_ROI = read.table(paste(ROImean_dir, in_name, sep = '/'),sep=" ",header=F)
out_ROI = read.table(paste(ROImean_dir, out_name, sep = '/'),sep=" ",header=F)

in_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
              in_ROI = in_ROI$V1)
in_df = merge(in_df, sub_control_df, by = "subjID")

out_df = cbind(list_fmri_df, age_bi = participant_demo_df$age_bi, 
              out_ROI = out_ROI$V1)
out_df = merge(out_df, sub_control_df, by = "subjID")

p_df = in_df %>% 
  mutate(out_ROI = out_df$out_ROI,
         DV = in_ROI - out_ROI,
         age_bi = relevel(as.factor(age_bi), ref = "younger")) %>% 
  select(-in_ROI, -out_ROI)

p_model = lm(DV~age_bi + tsnr + fd_mean + RT, p_df)
summary(p_model)

# partial_residual_p = 
  interact_plot(model_rlm_full, 
              pred = extrinsic_worsening_avg,
              modx = ses_2,
              plot.points = TRUE,
              jitter = c(0.05,0),
              data = mydata,
              partial.residuals = FALSE,
              point.alpha = 0.3,
              point.size = 0.7,
              x.label = IV1_xlabel_str,
              y.label = DV_ylabel_str,
              pred.labels = NULL,
              modx.labels = NULL,
              mod2.labels = NULL,
              main.title = NULL,
              legend.main = mod_legend_title_str)
```

## ggplot
```{r}

```


# Beh cov, para, act, in-out, norm_logit intercept * age, IPLD/IPLC
## prepare df for ggplot
```{r}
in_name = "cope-04.txt" # ingroup-04
out_name = "cope-06.txt" # outgroup-06

computer_df = read.table(paste(data_dir,computer_name,sep = '/'),sep=" ",header=F)
```

# Beh cov, para, ecn, in-out, sensitivity_logit * age, frontal pole/mpfc?
## prepare df for ggplot
```{r}

```






