---
title: "behavior_hypotheses_tests_srndnaUGR"
author: "Jen Yang"
date: "2024-11-1, last modified 2024-11-1"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
```

# dir and sub info
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"
data_dir = paste(gitrepo_path,"data", sep = "/")
# load L3 subs as in L3 template
L3_plain_df = read.csv(file = paste(data_dir, "participant_L3_47.csv", sep = "/"), header = TRUE)

```

# load behavior data
```{r}
rej_rate_df = read.csv(file = paste(data_dir, "rej_rate_partner_50.csv", sep = "/"), header = TRUE)
all_trials_df = read.csv(file = paste(data_dir, "all_trials.csv", sep = "/"), header = TRUE)
# sub_remove = c("sub-120","sub-131","sub-145")
# rej_rate_df = rej_rate_df[!rej_rate_df$subjID %in% sub_remove,]
```

# combine data frame using the subject order in L3_plain
## rejection rate
```{r}
rej_rate_L3_df = L3_plain_df
rej_colnames = colnames(rej_rate_df)[-1]
rej_rate_L3_df[, c("age", rej_colnames)] = NA
for (i in 1:nrow(L3_plain_df)) {
  sub_i = L3_plain_df$subjID[i]
  rej_rate_L3_df[i,rej_colnames] = rej_rate_df[rej_rate_df$subjID == sub_i, rej_colnames]
  rej_rate_L3_df$age[i] = participant_check_df$age[participant_check_df$participant_id == sub_i]
}

rej_rate_L3_df = rej_rate_L3_df %>% 
  mutate(
    # age_mean = age - mean(age),
         young = case_when(age <=36 ~ 1,
                           age > 36 ~ 0),
         old = case_when(age <=36 ~ 0,
                           age > 36 ~ 1),
         in_out = ingroup_rej_rate - outgroup_rej_rate,
         in_out_demean = in_out - mean(in_out),
         in_computer = ingroup_rej_rate - computer_rej_rate,
         in_computer_demean = in_computer - mean(in_computer),
         out_computer = outgroup_rej_rate - computer_rej_rate,
         out_computer_demean = out_computer - mean(out_computer),
         soc_nonsoc = 0.5 * (ingroup_rej_rate + outgroup_rej_rate) - computer_rej_rate,
         soc_nonsoc_demean = soc_nonsoc - mean(soc_nonsoc)
  )
```

### in_out_age_bi_df
```{r}
in_out_age_bi_df = rej_rate_L3_df %>% 
  mutate(in_out_young = in_out_demean*young,
         in_out_old = in_out_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         in_out_young, in_out_old)
write.csv(in_out_age_bi_df, paste(data_dir, "in_out_age_rej.csv", sep = "/"),
          row.names = FALSE)
```

### soc_nonsoc_age_bi_df
```{r}
soc_nonsoc_age_bi_df = rej_rate_L3_df %>% 
  mutate(soc_nonsoc_young = soc_nonsoc_demean*young,
         soc_nonsoc_old = soc_nonsoc_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         soc_nonsoc_young, soc_nonsoc_old)
write.csv(soc_nonsoc_age_bi_df, paste(data_dir, "soc_nonsoc_age_rej.csv", sep = "/"),
          row.names = FALSE)
```

## fairness sensitivity and norm
```{r}
reject_fairness_cols = c("subjID", "partner", "offer", "rejection")
reject_fairness_df = data.frame(matrix(nrow = 0, ncol = length(reject_fairness_cols)))
colnames(reject_fairness_df) = reject_fairness_cols

partner = c("computer", "ingroup", "outgroup")
partner_coding_human = c(0, 1, 1)
partner_coding_group = c(0, 1, 0)

for (i in 1:nrow(L3_plain_df)) {
  # i = 1
  sub_i = L3_plain_df$subjID[i]
  all_i = all_trials_df[all_trials_df$subjID == sub_i,]
  for (p in 1:length(partner)) {
    # p = 1
    partner_p = partner[p]
    partner_human = partner_coding_human[p]
    partner_group = partner_coding_group[p]
    all_i_p = all_i[all_i$human == partner_human & all_i$ingroup == partner_group,]
    offer_unique = sort(unique(all_i_p$offer))
    for (f in 1:length(offer_unique)) {
      # f = 1
      offer_f = offer_unique[f]
      all_i_p_f = all_i_p[all_i_p$offer == offer_f,]
      sum_f = nrow(all_i_p_f)
      reject_f = nrow(all_i_p_f) - sum(all_i_p_f$accept)
      nrow_df = nrow(reject_fairness_df)
      reject_fairness_df[nrow_df+1,] = 
        c(sub_i, partner_p, offer_f, reject_f/sum_f)
    }
  } 
}

reject_fairness_df <- reject_fairness_df %>%
  mutate(
    subjID = as.factor(subjID),
    partner = as.factor(partner),
    offer = as.numeric(offer) - 5, # center offer size to 5 for interpretation of intercept as a proxy of individual norm
    rejection = as.numeric(rejection),
  )
```

### individual slope and intercept
```{r}
fair_sense_cols = reject_fairness_cols = c("subjID", "partner", "slope", "intercept_5", "rejection_average")
fair_sense_df = data.frame(matrix(nrow = 0, ncol = length(fair_sense_cols)))
colnames(fair_sense_df) = fair_sense_cols

for (s in 1:nrow(L3_plain_df)) {
  # s = 5
  sub_s = L3_plain_df$subjID[s]
  df_s = reject_fairness_df[reject_fairness_df$subjID == sub_s,]
  for (ps in 1:length(partner)) {
    # ps = 2
    partner_ps = partner[ps]
    df_ps = df_s[df_s$partner == partner_ps,]
    # check if a sub reject or accept all
    vari_check_ps = mean(df_ps$rejection)
    
    model_ps = lm(rejection~offer, data = df_ps)
    # summary(model_ps)
    slope_ps <- model_ps$coefficients[2]
    if (vari_check_ps == 0) { # accept all
      intercept_5_ps <- 0
    } else if(vari_check_ps == 1) {
      intercept_5_ps <- 20
    } else {
      intercept_5_ps <- model_ps$coefficients[1]
    }
    nrow_ps = nrow(fair_sense_df)
    fair_sense_df[nrow_ps+1,] = c(sub_s, partner_ps, slope_ps, intercept_5_ps, vari_check_ps)
  }
}

fair_sense_df = fair_sense_df %>% 
  mutate(slope = as.numeric(slope),
         intercept_5 = as.numeric(intercept_5))

slope_fair_sense_df = fair_sense_df[,c("subjID", "partner", "slope")]
slope_fair_sense_wide_df <- slope_fair_sense_df %>%
  pivot_wider(names_from = partner, values_from = slope)

intercept_5_fair_sense_df = fair_sense_df[,c("subjID", "partner", "intercept_5")]
intercept_5_fair_sense_wide_df <- intercept_5_fair_sense_df %>%
  pivot_wider(names_from = partner, values_from = intercept_5)

sensitivity_df = merge(L3_plain_df, slope_fair_sense_wide_df, by.x = "subjID")
norm_df =   merge(L3_plain_df, intercept_5_fair_sense_wide_df, by.x = "subjID")
```

### fairness sensitivity for L3
```{r}
sensitivity_df = sensitivity_df %>% 
  mutate(
    # age_mean = age - mean(age),
    young = younger,
    old = older,
    in_out = ingroup - outgroup,
    in_out_demean = in_out - mean(in_out),
    soc_nonsoc = 0.5 * (ingroup + outgroup) - computer,
    soc_nonsoc_demean = soc_nonsoc - mean(soc_nonsoc)
  )
```

#### in_out_age_bi_df
```{r}
in_out_age_bi_df = sensitivity_df %>% 
  mutate(in_out_young = in_out_demean*young,
         in_out_old = in_out_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         in_out_young, in_out_old)
write.csv(in_out_age_bi_df, paste(data_dir, "in_out_age_sensitivity.csv", sep = "/"),
          row.names = FALSE)
```

#### soc_nonsoc_age_bi_df
```{r}
soc_nonsoc_age_bi_df = sensitivity_df %>% 
  mutate(soc_nonsoc_young = soc_nonsoc_demean*young,
         soc_nonsoc_old = soc_nonsoc_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         soc_nonsoc_young, soc_nonsoc_old)
write.csv(soc_nonsoc_age_bi_df, paste(data_dir, "soc_nonsoc_age_sensitivity.csv", sep = "/"),
          row.names = FALSE)
```


### norm for L3
```{r}
norm_df = norm_df %>% 
  mutate(
    # age_mean = age - mean(age),
    young = younger,
    old = older,
    in_out = ingroup - outgroup,
    in_out_demean = in_out - mean(in_out),
    soc_nonsoc = 0.5 * (ingroup + outgroup) - computer,
    soc_nonsoc_demean = soc_nonsoc - mean(soc_nonsoc)
  )
```

#### in_out_age_bi_df
```{r}
in_out_age_bi_df = norm_df %>% 
  mutate(in_out_young = in_out_demean*young,
         in_out_old = in_out_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         in_out_young, in_out_old)
write.csv(in_out_age_bi_df, paste(data_dir, "in_out_age_norm.csv", sep = "/"),
          row.names = FALSE)
```

#### soc_nonsoc_age_bi_df
```{r}
soc_nonsoc_age_bi_df = norm_df %>% 
  mutate(soc_nonsoc_young = soc_nonsoc_demean*young,
         soc_nonsoc_old = soc_nonsoc_demean*old) %>% 
  select(subjID, ismale, tsnr, fd_mean, RT, 
         young, old,
         soc_nonsoc_young, soc_nonsoc_old)
write.csv(soc_nonsoc_age_bi_df, paste(data_dir, "soc_nonsoc_age_norm.csv", sep = "/"),
          row.names = FALSE)
```