---
title: "fmri plot for SANS talk"
author: "Jen Yang"
date: "2025-04-10, last modified 2025-04-10"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
library(LMMstar)
```

```{r}
set.seed(123)
```

# directories
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")
```

# load and prepare data
```{r}
# load subs
all_trials_df = read.csv(paste(data_dir, "all_trials_brains.csv", sep = "/"), header = TRUE) %>% 
  .[.$missed == 0,]

colnames(all_trials_df)[colnames(all_trials_df) == "subjID"] <- "participant_id"
indiv_df = read.csv(paste(data_dir, "participant_check.csv", sep = "/"), header = TRUE)  %>%
  mutate(age_bi = case_when(age <= 36 ~ "younger",
                            age > 36 ~ "older"))

all_trials_df = merge(all_trials_df, indiv_df, by.x = "participant_id", by.y = "participant_id")

sublist_final = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"), header = TRUE)

all_trials_df = all_trials_df[all_trials_df$participant_id %in% sublist_final$subjID,]
```

## recode group and age
```{r}
## add a categorical variable that differentiate three groups
all_trials_df = all_trials_df %>% 
  mutate(group_tri = as.factor(case_when(human == 0 ~ 0, # computer
                               human == 1 & ingroup == 0 ~ 1, # outgroup
                               human == 1 & ingroup == 1 ~ 2))) # ingroup
# all_trials_df$group_tri = relevel(all_trials_df$group_tri, ref = "0") # computer

all_trials_df = all_trials_df %>% mutate(human = as.factor(human))

all_trials_df$group_tri = relevel(all_trials_df$group_tri, ref = "1") # outgroup

all_trials_df$age_bi = relevel(as.factor(all_trials_df$age_bi), ref = "younger")

all_trials_df = all_trials_df %>% 
  mutate(age_bi_dummy = case_when(age_bi == "younger" ~ 0,
                                  age_bi == "older" ~ 1)
         )
```

## factorize vars as needed
```{r}
factor_col_names = c("participant_id", "run", "missed", "accept",
                     "ingroup", "block_fair", "sex")
all_trials_df[factor_col_names] %<>% lapply(., factor) 
```

## add fdmean, tsnr vars to data
```{r}
fmri_control_data = 
  read.csv(paste(data_dir, "Task-ultimatum_Level-Run_Outlier-info.csv", 
                 sep = "/"), header = TRUE) %>% 
  filter(Sub %in% sublist_final$subjID == 1) %>% 
  # mutate(subjID = Sub) %>% 
  select(-task, -outlier_run_Custom1)

all_trials_df = merge(all_trials_df, fmri_control_data, 
                      by.x = c("participant_id", "run"),
                      by.y = c("Sub", "run"))
```

# plot param setup
```{r}
axis_title = 16
axis_ticks = 10
axis_text = 12
axis_label = 14

legend_all = 12

annotate_text = 4
axis_line_width = 1
fit_line_width = 2

data_point_alpha = 0.5
data_point_size = 3*0.8

mean_point_size = 3

summary_point_alpha = 1
summary_point_size = 3

annotate_text = 4

w = 5
h = 4
```

# anterior insula ~ choice * age * group3 + controls
## prep plot data
```{r}
plot_df = all_trials_df %>% 
  select(participant_id, 
         anteriorinsula_corrected,
         accept, group_tri, age_bi, 
         response_time, fd_mean, tsnr)
```

## get partial residuals
```{r}
LMM_df = plot_df
formula_string = "anteriorinsula_corrected ~ accept*age_bi*group_tri + tsnr + fd_mean + response_time"
formula_LMM = as.formula(formula_string)
focal_var_names = c("(Intercept)", "accept", "age_bi", "group_tri")

## compute partial residual using LMM
pres_LMM_fit = lmm(formula_LMM, data = LMM_df)
LMM_df$partial_residual <- residuals(pres_LMM_fit, type = "partial", 
                         variable = focal_var_names)
```

## prepare partial residual summary barplot and error bars
```{r}
summary_LMM_df <- LMM_df %>%
  group_by(age_bi, group_tri, accept) %>%
  summarise(mean_partial = mean(partial_residual, na.rm = TRUE),
    se_partial = sd(partial_residual, na.rm = TRUE) / sqrt(n()))

summary_LMM_df$group_tri %<>%  relevel(ref = "0")

summary_LMM_df_human = summary_LMM_df %>% filter(group_tri != "0")
```

## ggplot and save
```{r}
x_label = "Partner"
y_label = "Anterior Insula"
title_label = ""

fill_label = "Choice"
fill_values = c("0" = "orange", "1"= "lightblue") # "#37ff37"

figure_name = "AntInsula_group_age_controls"

p_bar =
ggplot() +
  geom_col(data = summary_LMM_df_human, 
           aes(x = group_tri, y = mean_partial, group = accept,
               fill = accept), 
               # fill = group_tri, color = accept),
           position = position_dodge(width = 0.8), width = 0.7) +
  geom_errorbar(data = summary_LMM_df_human,
                aes(x = group_tri, 
                    ymin = mean_partial - se_partial, 
                    ymax = mean_partial + se_partial,
                    group = accept),
                width = 0.2, size = 0.5,
                position = position_dodge(width = 0.8)) +
  scale_fill_manual(values = fill_values,
                    labels = c("0" = "reject", "1" = "accept")) +
  facet_wrap(~ age_bi) +
  labs(x = x_label, y = y_label, fill = color_label, title = title_label) +
  scale_x_discrete(
    labels = c("1" = "dissimilar", "2" = "similar")) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "solid", size = 0.2) +
  theme(axis.line = element_line(linewidth = 1, colour = "black", linetype=1),
        legend.title = element_text(face = "bold"),
        # legend.position = "none",
        axis.text.x = element_text(size = axis_text), 
        axis.text.y = element_text(size = axis_text), 
        axis.title.x = element_text(size = axis_title, face="bold"), 
        axis.title.y = element_text(size = axis_title, face="bold"),
        strip.text.x = element_text(face = "bold", size = axis_text),
        # strip.background = element_blank(),
        strip.background = element_rect(fill = "lightgrey", colour = NA)) 

p_bar

ggsave(paste(figure_dir, paste(figure_name, "bar.png", sep = "_"),
             sep = "/"), p_bar, width = w*1.5, height = h)
```

# end of code