---
title: "behavior_hypotheses_tests_srndnaUGR"
author: "Jen Yang"
date: "2024-11-11, last modified 2024-11-11"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message_bi=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
library(afex)
library(oro.nifti)
library(neurobase)
library(abind)

```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")
mask_dir = "/Users/momocco/Documents/GitHub/srndna-ug/masks_neurosynth"

image_dir = "/Users/momocco/Documents/SRNDNA_UG_SingleTrial/derivatives/single_trials"

singletrial_name = "task-ultimatum_run-0%d_singletrial-Act.nii.gz"
```

# load subject list
```{r}
sublist_name = "participant_L3_47.csv"
sublist_df = read.csv(paste(data_dir, sublist_name, sep = "/"), header = TRUE) %>% 
  select(subjID)
```

# behavioral data and ROI names
```{r}
# trials_name = "all_trials.csv"
trials_name = "all_trials_missedIncluded.csv"
trials_all_df = read.csv(paste(data_dir, trials_name, sep = "/"), header = TRUE)
trials_brains_all_df = trials_all_df

ROI_names = c("anteriorinsula", "dacc", "VS", "vmpfc")
trials_brains_all_df[ROI_names] = NA

ROI_nii_names = c(sprintf("bi_nanRemoved_resliced_%s_sphere5_mask.nii.gz", 
                          ROI_names))
```

# extract ROI means
```{r}
# check single trial dimension and behavior trial numbers
dim_check_col_names = c("subjID", "run", "single_trial", "behavior_hit")
dim_check_df = data.frame(matrix(NA, nrow = nrow(sublist_df)*2, ncol = length(dim_check_col_names)))
colnames(dim_check_df) = dim_check_col_names

for (sub_s in 1:nrow(sublist_df)) {
  # sub_s = 2 ### for testing
  subID_s = sublist_df$subjID[sub_s]
  print(subID_s)
  if (subID_s == "sub-104") {
    N_run = 1
  } else {N_run = 2}
  
  for (run_r in 1:N_run) {
    # run_r = 1 ### for testing
    dim_check_df$subjID[(sub_s-1)*2+run_r] = subID_s
    dim_check_df$run[(sub_s-1)*2+run_r] = run_r
    
    # extract trial N from behavior data
    N_trials_subID_r = sum(trials_all_df$subjID == subID_s & trials_all_df$run == run_r)
    dim_check_df$behavior_hit[(sub_s-1)*2+run_r] = N_trials_subID_r
    
    # Load the single trial NIFTI file
    single_name = paste(subID_s, sprintf(singletrial_name, run_r), sep = "_")
    # print(single_name)
    single_nii <- readNIfTI(paste(image_dir, subID_s, single_name, sep = "/"), reorient = FALSE)
    # extract image dimension
    single_dims = dim(single_nii)
    # print(single_dims)
    dim_check_df$single_trial[(sub_s-1)*2+run_r] = single_dims[4]
    # check if dimensions match
    
    if (single_dims[4] == N_trials_subID_r) { # if match, proceed to extract ROI means
      # dot product between 3D matrices along the 4th dimension, then sum, then divide by ROI size to get the mean
      print(sprintf("%s run %d OK", subID_s, run_r))
      single_df = single_nii[,,,] # 4D dataframe
      
      #######################################################################
      ###### extract ROI mean, loop through each sub and each ROI within a sub
      for (ROI_i in 1:length(ROI_names)) {
        # ROI_i = 2 ### for testing
        ROI_img = readNIfTI(paste(mask_dir, ROI_nii_names[ROI_i], sep = "/"), reorient = FALSE) # load image
        ROI_df = ROI_img[,,] # make 3D dataframe

        ROImean_vector <- sapply(
          1:single_dims[4], function(t) {
            sum(single_df[,,,t] * ROI_df)/sum(ROI_df==1)
          }
        )
        # add brain ROI mean to the end of behavior dataframe
        trials_brains_all_df[trials_brains_all_df$subjID == 
                               subID_s & trials_brains_all_df$run == run_r,
                             ROI_names[ROI_i]] = ROImean_vector
      }
      #######################################################################
      
    } else { # if dimensions don't match, print a message
      print(paste(subID_s,
                  sprintf("run %d total brain trial %d and total behavior trial %d don't match.",
                          run_r, single_dims[4], N_trials_subID_r), # show brain and behavior trial numbers
                  sep = " "))
    }
  }
}
```

# save check dataframe
```{r}
# dim_check_df$match = dim_check_df$single_trial == dim_check_df$behavior_hit
# write.csv(dim_check_df, paste(data_dir, "singletrial_behavior_check.csv", sep = "/"), row.names = FALSE)
```

# save full data
```{r}
write.csv(trials_brains_all_df, paste(data_dir, "singletrial_behavior_all.csv", sep = "/"), row.names = FALSE)
```

