---
title: "single-trial data autocorrelation check and clean"
author: "Jen Yang"
date: "2025-4-4, last modified 2025-4-4"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message_bi=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(emmeans)
library(mediation)
library(here)
library(lme4)
library(broom.mixed)
library(easyRT)
library(parameters)
library(effectsize)
library(effects)
library(lmerTest)
library(ez)
library(afex)
library(oro.nifti)
library(neurobase)
library(abind)
library(lmtest)
library(itsadug)
library(mgcv)
library(nlme)
library(arima2)
library(tseries)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")

trials_brains_all_df = read.csv(paste(data_dir, "singletrial_behavior_all.csv", sep = "/"), header = T)

sub_list = read.csv(paste(data_dir, "participant_L3_47.csv", sep = "/"), header = T) %>% 
  select(subjID)
N_sub = nrow(sub_list)
```

# check for autocorrelation per sub per run
```{r}
# create empty df to keep check info
auto_station_check_df = data.frame(matrix(nrow = N_sub*2, ncol = 1+1+4*2))
auto_col_names = c("subjID", "run", 
                         "anteriorinsula_auto", "anteriorinsula_stationary",
                         "dacc_auto", "dacc_stationary",
                         "VS_auto", "VS_stationary",
                         "vmpfc_auto", "vmpfc_stationary")
colnames(auto_station_check_df) = auto_col_names

trials_brains_all_df = trials_brains_all_df %>% 
  mutate(anteriorinsula_corrected = NA,
         dacc_corrected = NA,
         VS_corrected = NA,
         vmpfc_corrected = NA)

brain_names = c("anteriorinsula", "dacc", "VS", "vmpfc")

auto_df_cols = c("subjID", "run", "missed", "brain")

for (sub_s in 1:N_sub) {
  # sub_s = 1 ### for
  subID_s = sub_list[sub_s, "subjID"]
  print(subID_s)
  N_run = 2
  if (subID_s == "sub-104") {
    N_run = 1
  }
  
  # loop through runs
  for (run_r in 1:N_run) { 
    # run_r = 1 ### for testing
    auto_station_check_df[(sub_s-1)*2+run_r, "subjID"] = subID_s
    auto_station_check_df[(sub_s-1)*2+run_r, "run"] = run_r
    
    # loop through brain regions
    for (brain_b in 1:length(brain_names)) {
      # brain_b = 1 ### for testing
      brain_name_b = brain_names[brain_b] 
      sub_r_df = 
        trials_brains_all_df[trials_brains_all_df$subjID == subID_s & trials_brains_all_df$run == run_r, c("subjID", "run", "missed", brain_name_b)]
      
      # sub_r_df = sub_r_df[sub_r_df$missed == 0,] # removed missed trials
      colnames(sub_r_df) = auto_df_cols # change column names for later use in lm()
      
      # test for stationary time series
      ts_stationary = adf.test(sub_r_df$brain)
      ts_stationary_p = ts_stationary$p.value
      if (ts_stationary_p > 0.05) { # NON stationary, diff needed
        auto_station_check_df[(sub_s-1)*2+run_r, paste(brain_name_b,"_stationary", sep = "")] = 0
        # transform to stationary time series
        sub_r_df$brain = c(NA, diff(sub_r_df$brain))
      } else { # stationary, no diff needed
        auto_station_check_df[(sub_s-1)*2+run_r, paste(brain_name_b,"_stationary", sep = "")] = 1
      }
      
      # test for autocorrelation using Durbin-Watson test
      auto_m = lm(brain ~ 1, sub_r_df)
      auto_dw_test <- dwtest(auto_m)
      # extract results and save info
      dw_p = auto_dw_test$p.value
      if (dw_p > 0.05) { # NO autocorrelation, no correction needed
        auto_station_check_df[(sub_s-1)*2+run_r, paste(brain_name_b,"_auto", sep = "")] = 0
        trials_brains_all_df[trials_brains_all_df$subjID == subID_s & trials_brains_all_df$run == run_r,
                             paste(brain_name_b, "corrected", sep = "_")] = sub_r_df$brain
          
      } else { # autocorrelation, correction needed
        auto_station_check_df[(sub_s-1)*2+run_r, paste(brain_name_b,"_auto", sep = "")] = 1
        brain_ar_m = arima2::arima(sub_r_df$brain, order = c(1,0,0)) 
        brain_corrected <- residuals(brain_ar_m)
        trials_brains_all_df[trials_brains_all_df$subjID == subID_s & trials_brains_all_df$run == run_r,
                             paste(brain_name_b, "corrected", sep = "_")] = brain_corrected
      }
    }
  }
}

# write.csv(trials_brains_all_df, paste(data_dir, "all_trials_brains.csv", sep = "/"), row.names = FALSE)
```

# correct for autocorrelation
```{r}
###########################################################
      ############### correct for autocorrelation ###############
      rho_auto <- start_value_rho(auto_m, plot = F)
      # Add AR.start column to indicate start of time series
      sub_r_df$AR.start <- c(TRUE, rep(FALSE, nrow(sub_r_df) - 1))
      
      # Apply AR(1) correction using bam()
      auto_m_corrected <- bam(brain ~ 1, 
                              data = sub_r_df, 
                              rho = rho_auto, 
                              AR.start = AR.start)
      
      
      # Extract corrected residuals (autocorrelation-adjusted vector)
      corrected_vector <- resid(auto_m_corrected)
      
      # Validate correction by checking autocorrelation in corrected residuals
      acf_corrected <- acf(corrected_vector, lag.max = 1, plot = FALSE)
      cat("Corrected lag-1 autocorrelation:", round(acf_corrected$acf[2], 3), "\n")
      
      # Extract corrected residuals (your adjusted vector)
      corrected_vector <- resid(auto_m_corrected)
      
      ###########################################################
```

