---
title: "STAN_inspection"
author: "Jen Yang"
date: "2024-12-03"
output: html_document
---

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(rstan)
library(easystats)
library(patchwork)
library(brms)

```

# define dir and load data
```{r}
# gitrepo_path = here()
gitrepo_path = "/Users/momocco/Documents/GitHub/ddm-istart-DgUgpUgr"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fit_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")
pheno_dir = paste(gitrepo_path,"phenotype", sep = "/")
```

# prepare data
```{r}
questionnaires_wide_all_name = "questionnaires_wide_all.csv"
questionnaires_df = read.csv(paste(data_dir, questionnaires_wide_all_name, sep = "/"), header = TRUE)
# names(rand_indiv_wide_df)
sjdm_wide_df = questionnaires_df %>% 
  select("participant_id", "score_tei_emotionality") %>% na.omit() %>% 
  mutate(emotionality_norm = scale(score_tei_emotionality, center = TRUE, scale = TRUE)[,1]) %>% 
  select(participant_id, emotionality_norm)

UG_r_df = read.csv(paste(data_dir,"choice_UG_r.csv", sep = "/"), header = T)

UG_r_df = UG_r_df %>% mutate(resp_label_binary = recode(resp_label, "upper" = 1, "lower" = 0),
                            offer_percent = (L_Option + R_Option)/Endowment,
                            offer_size = L_Option + R_Option)

all_df = merge(UG_r_df, sjdm_wide_df, all.x=TRUE, by.y ="participant_id") %>% 
  na.omit() %>% 
  mutate(offer_percent_norm = scale(offer_percent, center = TRUE, scale = TRUE)[,1],
         Endowment_norm = scale(Endowment, center = TRUE, scale = TRUE)[,1]) %>% 
  select(participant_id,resp_label_binary, 
         offer_percent_norm, Endowment_norm, 
         emotionality_norm,
         offer_percent,
         rt, resp_label)
```

```{r}
## model_theory_033 (convg!)
model_UGR_link_theory_log_033 <- 
  bf(rt | dec(resp_label) ~ offer_percent_norm * emotionality_norm + 
       (1 + offer_percent_norm|participant_id), # drift rate
     bs ~ Endowment_norm + (1|participant_id), # boundary separation
     ndt ~ 1, # non-decision time
     bias ~ 1 # starting point bias
  ) 

# link functions. also the default of brm()
family <- wiener(
  link_bs = "log",
  link_ndt = "log",
  link_bias = "logit")

priors_auto = get_prior(model_UGR_link_theory_log_033,
                        data = all_df,
                        family = family)

stan_code <- make_stancode(model_UGR_link_theory_log_033, data = all_df, family = family)
print(stan_code)
```

