---
title: "matlab ugRL fit check"
author: "Jen Yang"
date: "2024-12-12, last modified 2024-12-12"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
```

# load tsv and prolific raw data
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fits_dir = paste(gitrepo_path,"fits", sep = "/")
figure_dir = paste(gitrepo_path,"figures", sep = "/")

bids_dir = "/Users/momocco/Documents/GitHub/srndna-datapaper/bids"
```

# load functions
```{r}
source(paste(codes_dir, "posterior_histo_plot_fun.R", sep = "/"))
```

# data prep
```{r}
# load sub list
participant_name = "sub_include.csv"
participants_df = read.table(file = paste(data_dir, participant_name, sep = "/"), header = TRUE)

posterior_names = c('alpha_i', 'tau_i', 'epsilon_i')
prior_names = c('alpha0', 'tau0', 'epsilon0', 'norm0')
```

# plot all posterior distribution
## alpha 0-20, tau 0-10, norm0 customized based on choice
```{r}
cvs_suff = "_ugrRL.csv"
fig_folder = "ugRL_alpha20tau10"

for (i in 1:nrow(participants_df)) {
  participants_df[i]
  posterior_histo_plot_fun(i, cvs_suff, fig_folder)
}
```

## alpha 0-30, tau 0-10, norm0 customized based on choice
```{r}
cvs_suff = "_alpha0_30_ugrRL.csv"
fig_folder = "ugRL_alpha30tau10"

for (i in 1:nrow(participants_df)) {
  print(participants_df$subjID[i])
  posterior_histo_plot_fun(i, cvs_suff, fig_folder)
}
```

## GU paper, norm0 variable 0-20
```{r}
cvs_suff = "_GUpaper_ugrRL.csv"
fig_folder = "ugRL_GUpaper"

for (i in 1:nrow(participants_df)) {
  print(participants_df$subjID[i])
  posterior_histo_plot_fun(i, cvs_suff, fig_folder)
}
```
## alpha 0-1, tau 0-1, norm0 customized based on choice
```{r}
cvs_suff = "_alpha0_1_ugrRL.csv"
fig_folder = "ugRL_alpha1tau1"

for (i in 1:nrow(participants_df)) {
  print(participants_df$subjID[i])
  posterior_histo_plot_fun(i, cvs_suff, fig_folder)
}
```


# stats test of corr
```{r}
# prior_posterior_lm_fun = function(prior_name, sub_df) {
  sub_df = sub_i_fit
prior_check = lm(sub_df[,'norm0'] ~ alpha_i + epsilon_i + tau_i, data = sub_df)

prior_p_values <- summary(prior_check)$coefficients[2:4, "Pr(>|t|)"]
prior_p_values_df <- as.data.frame(t(prior_p_values))
prior_p_values_df$subjID[1] = "a"
prior_p_values_df = prior_p_values_df %>% select(c('subjID', posterior_names))

summary(lm(alpha_i ~ epsilon_i, data = sub_df))
summary(lm(alpha_i ~ tau_i, data = sub_df))
summary(lm(tau_i ~ epsilon_i, data = sub_df))
# return()
# }
```

# plot function
```{r}
prior_posteriors_plots_fun <- function(df, prior_name) {
df = sub_i_fit # for testing
# df = sub_i_fit
prior_name = "alpha0"
df_current = df[, c(prior_name, posterior_names)]
plots <- list()
for (col_posterior in names(df_current)) {
  if (col_posterior != prior_name) {
    # col_posterior = "alpha_i"
    p = ggplot(df, aes_string(x = col_posterior, y = prior_name)) +
      geom_point() +
      geom_smooth(method = 'lm', se = FALSE, color = 'blue') +
      theme_minimal()
    plots[[col_posterior]] <- p
  }
}
plots
  return(plots)
}
```





