---
title: "matlab ugRL fit param extract"
author: "Jen Yang"
date: "2024-12-19, last modified 2024-12-19"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
```

# dirs
```{r}
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses"

data_dir = paste(gitrepo_path,"data", sep = "/")
codes_dir = paste(gitrepo_path, "codes", sep = "/")
fits_dir = paste(gitrepo_path,"fits", sep = "/")
figures_dir = paste(gitrepo_path,"figures", sep = "/")
```

# load functions
```{r}
source(paste(codes_dir, "posterior_fminsearch_histo_plot_fun.R", sep = "/"))
source(paste(codes_dir, "corrMatrix_upper_fun.R", sep = "/"))
source(paste(codes_dir, "corrMatrix_plot_fun.R", sep = "/"))
source(paste(codes_dir, "bestie_extract_fun.R", sep = "/"))
```

# data prep
```{r}
# load sub list
participant_name = "sub_39.csv"
participants_df = read.csv(file = paste(data_dir, participant_name, sep = "/"), header = TRUE)

posterior_names = c('alpha_i', 'tau_i', 'epsilon_i')
prior_names = c('alpha0', 'tau0', 'epsilon0', 'norm0')

norm0_df = read.csv(file = paste(fits_dir, "sub_include_norm0_guess.csv", sep = "/"), 
                      header = TRUE)
# choice_all_df = read.csv(paste(data_dir, "all_clean_filtered_df.csv", sep = "/"), header = T)
# computer_df = read.table(paste(data_dir, "computer_filtered.txt", sep = "/"), sep = "\t", header = T)
```

# prepare dataframe for point estimates of params
```{r}
alpha_esti_df = data.frame(subjID = participants_df$subjID,
                           computer = NA,
                           ingroup = NA,
                           outgroup = NA) 

epsilon_esti_df = data.frame(subjID = participants_df$subjID,
                           computer = NA,
                           ingroup = NA,
                           outgroup = NA)
```

## min negLL+1
```{r}
cvs_mid = "_alphaRANDtauRANDnorm0informedUPDATED_ugrRL_fminsearch_"
partner_types = c("computer", "ingroup", "outgroup")
for (i in 1:nrow(participants_df)) {
  # i = 4
  sub_i_name = participants_df$subjID[i]
  for (t in 1:length(partner_types)) {
    # t = 3
    param_type_t = partner_types[t]
    cvs_suff = paste(cvs_mid, param_type_t, ".csv", sep = "")
    peakmax_alpha_epsilon = bestie_extract_fun(sub_i_name, cvs_suff, param_type_t)
    alpha_esti_df[alpha_esti_df$subjID == sub_i_name,param_type_t] = peakmax_alpha_epsilon[1]
    epsilon_esti_df[epsilon_esti_df$subjID == sub_i_name, param_type_t] = peakmax_alpha_epsilon[2]
  }
}

write.csv(alpha_esti_df, paste(fits_dir, "alpha_39_1.csv", sep = "/"))
write.csv(epsilon_esti_df, paste(fits_dir, "epsilon_39_1.csv", sep = "/"))
```

