---
title: "fairness sensitivty based on lmer results"
author: "Jen Yang"
date: "2025-5-08, last modified 2025-5-09"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)
library(jsonlite)
library(rjson)
library(readr)
library(hBayesDM)
library(brms)
library(lme4)
library(lmerTest)
```

# set directories and file names
```{r}
# current code location
gitrepo_path = "/Users/momocco/Documents/GitHub/srndna-ug/behavioral_analyses/codes/RF1_UGR"

# subject list file names
sublist_L3_name = "sublist_L3_example.csv"
sublist_run_name = "sub_run_inclusion_example.csv"

# raw behavior data directory
UGR_behavior_raw_path =
  "/Users/momocco/Documents/GitHub/rf1-sra/stimuli/Scan-Lets_Make_A_Deal/logs"
```

## define folder to save fit results
```{r}
# location to save fits
fit_dir = paste(gitrepo_path,"fits", sep = "/")

# create the fits folder it it doesn't exist
if (!dir.exists(fit_dir)) {
  dir.create(fit_dir)
}
```

# prepare behavior data
## load subject L3 list and subject-run check list
```{r}
# load subject run inclusion list
sub_L3_list = read.csv(paste(gitrepo_path, sublist_L3_name, sep = "/"),
                       header = TRUE)

sub_run_list = read.csv(paste(gitrepo_path, sublist_run_name, sep = "/"),
                       header = TRUE)

sub_L3_run_uni_list = merge(sub_L3_list, sub_run_list, 
                            by.x = "subjID")
```

## set seed for reproducibility
```{r}
set.seed(20250508)
```

## compile data based on sub L3 and run inclusion list
```{r}
# create empty dataframe to save cleaned behavior data
col_names = c('subjID', 'partner', 
              'offer_percent', 'decision', 
              'offer_dollar', 'Endowment', "run")
UGR_clean_all = data.frame(matrix(nrow = 0, ncol = length(col_names)))

sub_N = nrow(sub_L3_run_uni_list)

for (s in 1:nrow(sub_L3_run_uni_list)) { # start of sub loop
  # s = 1
  sub_s = sub_L3_run_uni_list$subjID[s]
  
  # extract run inclusion information
  run_check = c(sub_L3_run_uni_list$run1[s], sub_L3_run_uni_list$run2[s])
  
  ## run loop
  r_N = 2
  for (r in 1:r_N) {
    # r = 1
    run_id = r-1
    r_check = run_check[r]
    
    if (r_check == 1) {
      behavior_s_r_name = sprintf("sub-%d_task-ultimatum_run-%d_raw.csv",
                                  as.numeric(sub_s), run_id)
      behavior_s_r_raw_df = 
        read.csv(paste(UGR_behavior_raw_path, 
                       sub_s,
                       behavior_s_r_name, sep = "/"), header = TRUE)
      
      # recode condition and response
      ## condition:  1 = Commented out, 2 = Nonsocial, 3 = Social
      ## response: 1 = left, 2 = right
      behavior_s_r_df = behavior_s_r_raw_df %>% 
        mutate(decision = case_when(resp == 1 & L_Option == 0 ~ "reject",
                                    resp == 1 & L_Option > 0 ~ "accept",
                                    resp == 2 & R_Option == 0 ~ "reject",
                                    resp == 2 & R_Option > 0 ~ "accept",
                                    resp == 999 ~ NA),
               offer_percent = (L_Option + R_Option)/Endowment,
               offer_dollar = L_Option + R_Option,
               partner = case_when(Block == 2 ~ "Nonsocial",
                                   Block == 3 ~ "Social"),
               subjID = sprintf("sub-%d", as.numeric(sub_s)),
               run = r) %>% 
        select(col_names)
      
      UGR_clean_all = rbind(UGR_clean_all, behavior_s_r_df)
    }
  } # end of run loop
} # end of sub loop

UGR_clean_all = UGR_clean_all %>% 
  na.omit() %>% 
  mutate(partner = relevel(as.factor(partner), ref = "Nonsocial"),
         decision = relevel(as.factor(decision), ref = "reject"))

```

# extract sensitivity
## Social
```{r}
## Social offer sensitivity
Social_df = filter(UGR_clean_all, partner == "Social")

Social_mlm_1 = glmer(decision ~ offer_percent + (1 + offer_percent|subjID), 
                 data = Social_df, 
                 family = binomial)

## assuming correlation between random slope and random intercept provided better fit based on anova() outcom
# Social_mlm_2 = glmer(decision ~ offer_percent + (1 + offer_percent||subjID), 
#                  data = Social_df, 
#                  family = binomial)
# anova(Social_mlm_1, Social_mlm_2)

summary(Social_mlm_1)

Social_fixed_effects <- fixef(Social_mlm_1) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "fixed")

Social_random_effects <- ranef(Social_mlm_1, condVar = FALSE) %>% 
  as.data.frame()

Social_effects = Social_random_effects[Social_random_effects$term == "offer_percent",] %>% 
  mutate(Social_random = condval,
         Social_full = 
           condval + Social_fixed_effects$.[Social_fixed_effects$fixed == "offer_percent"],
         subjID = grp) %>% 
  dplyr::select(subjID, Social_random, Social_full)
```

## Nonsocial
```{r}
## Nonsocial offer sensitivity
Nonsocial_df = filter(UGR_clean_all, partner == "Nonsocial")

NonSocial_mlm_1 = glmer(decision ~ offer_percent + (1 + offer_percent|subjID), 
                     data = Nonsocial_df, 
                     family = binomial)

## assuming correlation between random slope and random intercept provided better fit based on anova() outcom
# NonSocial_mlm_2 = glmer(decision ~ offer_percent + (1 + offer_percent||subjID),
#                  data = Nonsocial_df,
#                  family = binomial)
# anova(NonSocial_mlm_1, NonSocial_mlm_2)
# 
# summary(NonSocial_mlm_1)

Nonsocial_fixed_effects <- fixef(NonSocial_mlm_1) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "fixed")

Nonsocial_random_effects <- ranef(NonSocial_mlm_1, condVar = FALSE) %>% 
  as.data.frame()

Nonsocial_effects = Nonsocial_random_effects[Nonsocial_random_effects$term == "offer_percent",] %>% 
  mutate(Nonsocial_random = condval,
         Nonsocial_full = 
           condval + Nonsocial_fixed_effects$.[Nonsocial_fixed_effects$fixed == "offer_percent"],
         subjID = grp) %>% 
  dplyr::select(subjID, Nonsocial_random, Nonsocial_full)
```

# save
```{r}
soc_nonsoc_sens_df = merge(Social_effects, Nonsocial_effects, 
                           by.x = "subjID", by.y = "subjID") %>% 
  mutate(Soc_Nonsoc_diff =  Social_full - Nonsocial_full) %>% 
  select(subjID, Social_full, Nonsocial_full, Soc_Nonsoc_diff)
write.csv(soc_nonsoc_sens_df, 
          paste(fit_dir, "RF1_UGR_sensitivity_logit.csv", sep = "/"),
          row.names = FALSE)
```
